#ifndef MEMORY_ARBITRATION_H
#define MEMORY_ARBITRATION_H

#define JAILHOUSE_MEMORY_ARBITRATION_SGI_MEMORY_PHASE_STARTED	13
#define JAILHOUSE_MEMORY_ARBITRATION_SGI_MEMORY_PHASE_ENDED	14

#endif /* MEMORY_ARBITRATION_H */