# ###*B*###
#
# ERIKA Enterprise - a tiny RTOS for small microcontrollers
# 
# Copyright (C) 2002-2018 Evidence Srl
# 
# This file is part of ERIKA Enterprise.
# 
# See LICENSE file.
#
# ###*E*###

############################################################################
#
# This file is generated by RT-Druid.
# Please do not modify it.
#
############################################################################

############################################################################
#
# User options
#
############################################################################
OS_EE_OPT += OSEE_DEBUG
OS_EE_OPT += OS_EE_APPL_BUILD_DEBUG
OS_EE_OPT += OS_EE_BUILD_DEBUG


############################################################################
#
# Automatic options
#
############################################################################
OS_EE_OPT += OSEE_AARCH64_CORE0_ISR_MAX_PRIO  (1U)
OS_EE_OPT += OSEE_AARCH64_SOC nvidia_tegra_x2
OS_EE_OPT += OSEE_API_DYNAMIC
OS_EE_OPT += OSEE_ARCH_AARCH64
OS_EE_OPT += OSEE_HAS_EVENTS
OS_EE_OPT += OSEE_HAS_IDLEHOOK
OS_EE_OPT += OSEE_HAS_RESOURCES
OS_EE_OPT += OSEE_ISR2_MAX_PRIO (128U)
OS_EE_OPT += OSEE_MULTI_STACK
OS_EE_OPT += OSEE_OC_ECC2
OS_EE_OPT += OSEE_PLATFORM_JAILHOUSE
OS_EE_OPT += OS_EE_GCC
OS_EE_OPT += OS_EE_KERNEL_OSEK
OS_EE_OPT += OS_EE_RTD_BUILD_ENV_NATIVE
OS_EE_OPT += OS_EE_RTD_DISABLE_OS_EE_OPT_DEFINES




JAILHOUSE_VERSION           := 0.9.1
export  JAILHOUSE_VERSION

JAILHOUSE_DIR               := /home/gschwaer/code/workspace/Erika_DPREM/jailhouse-master_dprem
export  JAILHOUSE_DIR

JAILHOUSE_AARCH64_GCCPREFIX := aarch64-linux-gnu-
export  JAILHOUSE_AARCH64_GCCPREFIX

OSEE_AARCH64_SOC := nvidia_tegra_x2
export OSEE_AARCH64_SOC


############################################################################
#
# Flags
#
############################################################################
CFLAGS  +=
CFLAGS  += -I../erika/src
CFLAGS  += -I../jailhouse-master_dprem/inmates/lib
CFLAGS  += -I../jailhouse-master_dprem/hypervisor
CFLAGS  += -I../jailhouse-master_dprem/hypervisor/include
CFLAGS  += -I../jailhouse-master_dprem/hypervisor/arch/arm64/include
CFLAGS  += -I../jailhouse-master_dprem/hypervisor/arch/arm-common/include
CFLAGS  += -I../jailhouse-master_dprem/include
CFLAGS  += -I../jailhouse-master_dprem/include/arch/arm64
CFLAGS  += -I../jailhouse-master_dprem/include/inmates/lib
CFLAGS  += -I../jailhouse-master_dprem/include/inmates/lib/arm64/include
CFLAGS  += -I../jailhouse-master_dprem/include/inmates/lib/arm-common/include
export CFLAGS

ASFLAGS +=
export ASFLAGS

LDFLAGS +=
export LDFLAGS

LDDEPS  +=
export LDDEPS

LIBS    +=
export LIBS


############################################################################
#
# Sources
#
############################################################################
OS_EE_CFG_SRCS +=
OS_EE_CFG_SRCS += ee_oscfg.c
export OS_EE_CFG_SRCS


############################################################################
#
# End
#
############################################################################

