/* ###*B*###
 *
 * ERIKA Enterprise - a tiny RTOS for small microcontrollers
 * 
 * Copyright (C) 2002-2018 Evidence Srl
 * 
 * This file is part of ERIKA Enterprise.
 * 
 * See LICENSE file.
 *
 * ###*E*### */

/***************************************************************************
 *
 * This file is generated by RT-Druid.
 * Please do not modify it.
 *
 **************************************************************************/

#ifndef OS_EE_RTD_OSCFG_H
#define OS_EE_RTD_OSCFG_H


/***************************************************************************
 *
 * Version Check
 *
 **************************************************************************/
#define OS_EE_RTD_GEN_VERSION 12345


/***************************************************************************
 *
 * Common defines
 *
 **************************************************************************/
#define OSEE_SINGLECORE
#define OsNumberOfCores         (1U)
#define OSEE_CORE_ID_VALID_MASK ((1U << 0))

/* Dynamic api: size of the array of all possible tasks for all cores (TDB) */
#define OSEE_TASK_ARRAY_SIZE (8U)

/* Dynamic api: size of the array of all possible scheduler nodes for all cores (SN) */
#define OSEE_SN_ARRAY_SIZE   (8U)

/* Dynamic api: size of the memory dedicated to contain all stacks */
#define OSEE_STACKS_SIZE     (8192U)

/***************************************************************************
 *
 * User options
 *
 **************************************************************************/
#define OSEE_DEBUG
#define OS_EE_APPL_BUILD_DEBUG
#define OS_EE_BUILD_DEBUG

/***************************************************************************
 *
 * Automatic options
 *
 **************************************************************************/
#define OSEE_AARCH64_CORE0_ISR_MAX_PRIO  (1U)
#define OSEE_AARCH64_SOC nvidia_tegra_x2
#define OSEE_API_DYNAMIC
#define OSEE_ARCH_AARCH64
#define OSEE_HAS_EVENTS
#define OSEE_HAS_IDLEHOOK
#define OSEE_HAS_RESOURCES
#define OSEE_ISR2_MAX_PRIO (128U)
#define OSEE_MULTI_STACK
#define OSEE_OC_ECC2
#define OSEE_PLATFORM_JAILHOUSE
#define OS_EE_GCC
#define OS_EE_KERNEL_OSEK
#define OS_EE_RTD_BUILD_ENV_NATIVE


/***************************************************************************
 *
 * Automatic OS options
 *
 **************************************************************************/




/***************************************************************************
 *
 * ISR1 declaration
 *
 **************************************************************************/

/***************************************************************************
 *
 * ISR2 declaration
 *
 **************************************************************************/

/***************************************************************************
 *
 * System Timer
 *
 **************************************************************************/

/***************************************************************************
 *
 * End
 *
 **************************************************************************/
#endif /* OS_EE_RTD_OSCFG_H */

